
services:
    database:
        image: postgres:15
        container_name: postgres_db
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: double_materiality_assessment
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data

    backend:
        build: 
            context: ./nest-backend
        container_name: nest_backend
        volumes:
            - ./nest-backend:/app
            - /app/node_modules 
        ports:
            - "4000:4000"
        depends_on:
            - database
        environment:
            WATCHPACK_POLLING: "true"
            DATABASE_URL: postgres://admin:password@database:5432/double_materiality_assessment?schema=public
    
    prisma-studio:
        build: 
            context: ./nest-backend
        container_name: prisma_studio
        working_dir: /app
        command: sh -c "npx prisma studio --port 5555 --browser none"
        volumes:
            - ./nest-backend:/app
            - node_modules:/app/node_modules
        ports:
            - "5555:5555"
        depends_on:
            - database
            - backend
        environment:
            DATABASE_URL: postgres://admin:password@database:5432/double_materiality_assessment?schema=public

    frontend:
        build: ./next-frontend
        container_name: next_frontend
        command: npm run dev
        volumes:
            - ./next-frontend:/app
            - /app/node_modules  
        ports:
            - "3000:3000"
        depends_on:
            - backend
        environment:
            NEXT_PUBLIC_API_URL: http://localhost:4000/graphql
            WATCHPACK_POLLING: "true" 

volumes:
    postgres_data:
    node_modules:
